version: 2

sources:
    - name: jaffle_shop
      schema: my_dbt_db
      description: E-commerce data for the Jaffle Shop

      tables:
        - name: raw_customers
          description: One record per person who has purchased one or more items
        - name: raw_orders